---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: opendns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.253
  selector:
    k8s-app: kube-dns
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53

---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: opendns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.253
  selector:
    k8s-app: kube-dns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53