ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-production
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.34.121.218.10.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.121.218.10.nip.io.secret
  certManager: true