expose:
  type: ingress
  tls:
    enabled: true
    certSource: auto
    auto:
      commonName: ""
    secret:
      secretName: "harbor.34.121.218.10.nip.io.secret"
      notarySecretName: ""
  ingress:
    hosts:
      core: harbor.34.121.218.10.nip.io
      notary: notary.harbor.domain
    controller: default
    kubeVersionOverride: ""
    className: ""
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-production
      cert-manager.io/acme-challenge-type: http01
    notary:
      annotations: {}
      labels: {}
    harbor:
      annotations: {}
      labels: {}

externalURL: https://harbor.34.121.218.10.nip.io

notary:
  enabled: false