apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: regull/k8s-intro-frontend:1
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}